name: Pull Request Workflow
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_approval:
    uses: chuongtruong/Test_env_var/.github/workflows/test_aprroval.yaml@Master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.head_ref }}